export * from "./Header";
export * from "./Footer";
export * from "./Feedback";
export * from "./FAQs";
export * from "./Services";
export * from "./Team";
export * from "./Partners";
export * from "./Adventages";
export * from "./Reviews";